before_script:

consul:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
    SERVERSPEC_TARGET: consul
    RAKE_TARGET: serverspec:${SERVERSPEC_TARGET}
  services:
    - docker:stable-dind
  script:
    - >
      apk --update add --virtual build-dependencies build-base ruby ruby-rdoc ruby-dev ruby-irb postgresql-dev ruby-etc
      libc-dev zlib-dev linux-headers git ruby-bigdecimal ruby-io-console libstdc++ tzdata postgresql-client
      nodejs libffi-dev curl wget py-pip ruby-webrick ruby-etc
    - gem install bundle
    - bundle install
    - bundle exec rake ${RAKE_TARGET}
