variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
services:
  - name: docker:stable-dind
    alias: localhost

before_script:
  - >
    apk --update add --virtual build-dependencies build-base ruby ruby-rdoc ruby-dev ruby-irb postgresql-dev ruby-etc
    libc-dev zlib-dev linux-headers git ruby-bigdecimal ruby-io-console libstdc++ tzdata postgresql-client
    nodejs libffi-dev curl wget py-pip ruby-webrick ruby-etc
  - gem install bundle
  - bundle install

docker_sevice: &container_config
  image: docker:stable
  variables: &task_variables
    DOCKER_DRIVER: overlay2
    SERVERSPEC_TARGET: service
    RAKE_TARGET: serverspec:${SERVERSPEC_TARGET}
  script:
    - bundle exec rake ${RAKE_TARGET}

docker_container:
  <<: *container_config
  variables:
    <<: *task_variables
    SERVERSPEC_TARGET: container

docker_network:
  <<: *container_config
  variables:
    <<: *task_variables
    SERVERSPEC_TARGET: network

docker_secret:
  <<: *container_config
  variables:
    <<: *task_variables
    SERVERSPEC_TARGET: secret

docker_config:
  <<: *container_config
  variables:
    <<: *task_variables
    SERVERSPEC_TARGET: config

docker_node:
  <<: *container_config
  variables:
    <<: *task_variables
    SERVERSPEC_TARGET: node

curl:
  <<: *container_config
  variables:
    <<: *task_variables
    SERVERSPEC_TARGET: curl

consul:
  <<: *container_config
  variables:
    <<: *task_variables
    SERVERSPEC_TARGET: consul

rabbitmq:
  <<: *container_config
  variables:
    <<: *task_variables
    SERVERSPEC_TARGET: rabbitmq

nfs_export:
  <<: *container_config
  variables:
    <<: *task_variables
    SERVERSPEC_TARGET: nfs_export

sudo:
  <<: *container_config
  variables:
    <<: *task_variables
    SERVERSPEC_TARGET: sudo

sudo_user:
  <<: *container_config
  variables:
    <<: *task_variables
    SERVERSPEC_TARGET: sudo_user

jenkins_plugin:
  <<: *container_config
  variables:
    <<: *task_variables
    SERVERSPEC_TARGET: jenkins_plugin
  services:
    - name: docker:stable-dind
      alias: localhost
