AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'serverspec-extra-types.gemspec'
    - 'util/mkcode.rb'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 140


Metrics/MethodLength:
 Max: 15

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'