AllCops:
  Exclude:
    - 'serverspec-extra-types.gemspec'

tyle/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 140


Metrics/MethodLength:
 Max: 15

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'